[postgres]
host = "localhost"
database = "sistema_compras"
username = "postgres"
password = "postgres123"
port = 5432

[database]
# URL de conexão completa (alternativa)
url = "postgresql://postgres:postgres123@localhost:5432/sistema_compras"
