# Credenciais do Neon DB - Sistema de Compras
[postgres]
host = "ep-quiet-wave-aexxyu7g-pooler.c-2.us-east-2.aws.neon.tech"
database = "neondb"
user = "neondb_owner"
password = "npg_GZJ7yawMprC5"
port = 5432
sslmode = "require"
