# Generated by Django 4.2.16 on 2025-09-15 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], max_length=10, verbose_name='Nível')),
                ('logger_name', models.CharField(max_length=100, verbose_name='Logger')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Módulo')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='Função')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='Linha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='Caminho da Requisição')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Dados Extras')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='auditoria_l_level_d602f1_idx'), models.Index(fields=['logger_name', 'timestamp'], name='auditoria_l_logger__fc1a6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tentativa', models.CharField(max_length=150, verbose_name='Username Tentativa')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('BLOCKED', 'Bloqueado')], max_length=10, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('motivo_falha', models.CharField(blank=True, max_length=255, verbose_name='Motivo da Falha')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('sessao_id', models.CharField(blank=True, max_length=40, verbose_name='ID da Sessão')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Login',
                'verbose_name_plural': 'Históricos de Login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='auditoria_h_usuario_84a39a_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auditoria_h_ip_addr_3da753_idx'), models.Index(fields=['status', 'timestamp'], name='auditoria_h_status_ab1e16_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=150, verbose_name='Nome do Usuário')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição'), ('MOVE', 'Movimentação'), ('CONFIG', 'Configuração'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('sessao_id', models.CharField(blank=True, max_length=40, verbose_name='ID da Sessão')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria Administrativa',
                'verbose_name_plural': 'Auditorias Administrativas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='auditoria_a_usuario_ff34ce_idx'), models.Index(fields=['acao', 'timestamp'], name='auditoria_a_acao_eaedb6_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_0efd41_idx')],
            },
        ),
    ]
