# Generated by Django 4.2.16 on 2025-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditoriaadmin',
            name='auditoria_a_content_0efd41_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaadmin',
            new_name='auditoria_a_usuario_dcb851_idx',
            old_name='auditoria_a_usuario_ff34ce_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaadmin',
            new_name='auditoria_a_acao_74f4cb_idx',
            old_name='auditoria_a_acao_eaedb6_idx',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='dados_anteriores',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='dados_novos',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='sessao_id',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='auditoriaadmin',
            name='usuario_nome',
        ),
        migrations.AddField(
            model_name='auditoriaadmin',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
        migrations.AddField(
            model_name='auditoriaadmin',
            name='modulo',
            field=models.CharField(default='Sistema', max_length=100, verbose_name='Módulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoriaadmin',
            name='solicitacao_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Solicitação'),
        ),
        migrations.AlterField(
            model_name='auditoriaadmin',
            name='ip_address',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=45, verbose_name='Endereço IP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoriaadmin',
            name='usuario',
            field=models.CharField(default='sistema', max_length=150, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='sessao_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID da Sessão'),
        ),
        migrations.AlterModelTable(
            name='auditoriaadmin',
            table='auditoria_admin',
        ),
    ]
