# Generated by Django 4.2.16 on 2025-09-15 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('unidade', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Produto do Catálogo',
                'verbose_name_plural': 'Produtos do Catálogo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao_estoque', models.IntegerField(unique=True, verbose_name='Número da Solicitação')),
                ('numero_requisicao', models.IntegerField(blank=True, null=True, verbose_name='Número da Requisição')),
                ('numero_pedido_compras', models.IntegerField(blank=True, null=True, verbose_name='Número do Pedido de Compras')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitante')),
                ('departamento', models.CharField(choices=[('Manutenção', 'Manutenção'), ('TI', 'TI'), ('RH', 'RH'), ('Financeiro', 'Financeiro'), ('Marketing', 'Marketing'), ('Operações', 'Operações'), ('Outro', 'Outro')], max_length=50, verbose_name='Departamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Normal', 'Normal'), ('Baixa', 'Baixa')], default='Normal', max_length=20, verbose_name='Prioridade')),
                ('local_aplicacao', models.CharField(max_length=200, verbose_name='Local de Aplicação')),
                ('status', models.CharField(choices=[('Solicitação', 'Solicitação'), ('Requisição', 'Requisição'), ('Suprimentos', 'Suprimentos'), ('Em Cotação', 'Em Cotação'), ('Pedido de Compras', 'Pedido de Compras'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Compra feita', 'Compra feita'), ('Aguardando Entrega', 'Aguardando Entrega'), ('Pedido Finalizado', 'Pedido Finalizado')], default='Solicitação', max_length=50, verbose_name='Status')),
                ('etapa_atual', models.CharField(choices=[('Solicitação', 'Solicitação'), ('Requisição', 'Requisição'), ('Suprimentos', 'Suprimentos'), ('Em Cotação', 'Em Cotação'), ('Pedido de Compras', 'Pedido de Compras'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Compra feita', 'Compra feita'), ('Aguardando Entrega', 'Aguardando Entrega'), ('Pedido Finalizado', 'Pedido Finalizado')], default='Solicitação', max_length=50, verbose_name='Etapa Atual')),
                ('carimbo_data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora Criação')),
                ('data_requisicao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Requisição')),
                ('responsavel_estoque', models.CharField(blank=True, max_length=100, verbose_name='Responsável Estoque')),
                ('data_numero_pedido', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pedido')),
                ('data_cotacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Cotação')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('sla_dias', models.IntegerField(default=3, verbose_name='SLA em Dias')),
                ('dias_atendimento', models.IntegerField(blank=True, null=True, verbose_name='Dias de Atendimento')),
                ('sla_cumprido', models.CharField(blank=True, max_length=10, verbose_name='SLA Cumprido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('numero_requisicao_interno', models.CharField(blank=True, max_length=50, verbose_name='Número Requisição Interno')),
                ('data_requisicao_interna', models.DateTimeField(blank=True, null=True, verbose_name='Data Requisição Interna')),
                ('responsavel_suprimentos', models.CharField(blank=True, max_length=100, verbose_name='Responsável Suprimentos')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Final')),
                ('fornecedor_recomendado', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor Recomendado')),
                ('fornecedor_final', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor Final')),
                ('anexos_requisicao', models.JSONField(blank=True, default=list, verbose_name='Anexos da Requisição')),
                ('cotacoes', models.JSONField(blank=True, default=list, verbose_name='Cotações')),
                ('aprovacoes', models.JSONField(blank=True, default=list, verbose_name='Aprovações')),
                ('historico_etapas', models.JSONField(blank=True, default=list, verbose_name='Histórico de Etapas')),
                ('itens', models.JSONField(blank=True, default=list, verbose_name='Itens da Solicitação')),
                ('data_entrega_prevista', models.DateTimeField(blank=True, null=True, verbose_name='Data Entrega Prevista')),
                ('data_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Data Entrega Real')),
                ('entrega_conforme', models.CharField(blank=True, max_length=10, verbose_name='Entrega Conforme')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal')),
                ('responsavel_recebimento', models.CharField(blank=True, max_length=100, verbose_name='Responsável Recebimento')),
                ('observacoes_entrega', models.TextField(blank=True, verbose_name='Observações da Entrega')),
                ('observacoes_finalizacao', models.TextField(blank=True, verbose_name='Observações da Finalização')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('tipo_solicitacao', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Solicitação')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('observacoes_requisicao', models.TextField(blank=True, verbose_name='Observações da Requisição')),
                ('observacoes_pedido_compras', models.TextField(blank=True, verbose_name='Observações do Pedido de Compras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-numero_solicitacao_estoque'],
                'indexes': [models.Index(fields=['numero_solicitacao_estoque'], name='solicitacoe_numero__04ed35_idx'), models.Index(fields=['status'], name='solicitacoe_status_e0f3eb_idx'), models.Index(fields=['solicitante'], name='solicitacoe_solicit_62d0b0_idx'), models.Index(fields=['departamento'], name='solicitacoe_departa_015260_idx'), models.Index(fields=['prioridade'], name='solicitacoe_priorid_094c60_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_origem', models.CharField(max_length=50, verbose_name='Etapa Origem')),
                ('etapa_destino', models.CharField(max_length=50, verbose_name='Etapa Destino')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='solicitacoes.solicitacao')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
