# Generated by Django 4.2.16 on 2025-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_numero__eb7a5e_idx',
            old_name='solicitacoe_numero__04ed35_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_status_99769b_idx',
            old_name='solicitacoe_status_e0f3eb_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_solicit_c59a37_idx',
            old_name='solicitacoe_solicit_62d0b0_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_departa_44933a_idx',
            old_name='solicitacoe_departa_015260_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_priorid_bc4bc9_idx',
            old_name='solicitacoe_priorid_094c60_idx',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='numero_solicitacao',
            field=models.IntegerField(default='Sistema', verbose_name='Número da Solicitação'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='catalogoproduto',
            table='catalogo_produtos',
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table='movimentacoes',
        ),
        migrations.AlterModelTable(
            name='solicitacao',
            table='solicitacoes',
        ),
    ]
