# Generated by Django 4.2.16 on 2025-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Inteiro'), ('float', 'Número Decimal'), ('boolean', 'Verdadeiro/Falso'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50, unique=True, verbose_name='Departamento')),
                ('sla_urgente', models.IntegerField(default=1, verbose_name='SLA Urgente (dias)')),
                ('sla_alta', models.IntegerField(default=2, verbose_name='SLA Alta (dias)')),
                ('sla_normal', models.IntegerField(default=3, verbose_name='SLA Normal (dias)')),
                ('sla_baixa', models.IntegerField(default=5, verbose_name='SLA Baixa (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de SLA',
                'verbose_name_plural': 'Configurações de SLA',
                'ordering': ['departamento'],
            },
        ),
        migrations.CreateModel(
            name='LimiteAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Limite')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Máximo')),
                ('aprovador_necessario', models.CharField(choices=[('Gerência', 'Gerência'), ('Diretoria', 'Diretoria'), ('Especial', 'Aprovação Especial')], max_length=50, verbose_name='Aprovador Necessário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Limite de Aprovação',
                'verbose_name_plural': 'Limites de Aprovação',
                'ordering': ['valor_minimo'],
            },
        ),
    ]
