# Generated by Django 4.2.16 on 2025-09-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='tipo',
        ),
        migrations.AlterModelTable(
            name='configuracao',
            table='configuracoes',
        ),
    ]
