# Generated by Django 4.2.16 on 2025-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='sessao',
            name='username',
            field=models.CharField(default='sistema', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_hash',
            field=models.CharField(default='', max_length=255, verbose_name='Senha Hash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('TI', 'TI'), ('RH', 'RH'), ('Financeiro', 'Financeiro'), ('Marketing', 'Marketing'), ('Operações', 'Operações'), ('Outro', 'Outro')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Solicitante', 'Solicitante'), ('Estoque', 'Estoque'), ('Suprimentos', 'Suprimentos'), ('Gerência&Diretoria', 'Gerência & Diretoria'), ('Admin', 'Administrador')], max_length=50, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
        migrations.AlterModelTable(
            name='sessao',
            table='sessoes',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
